sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 20040609

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJw3ympz6LepGUqpyNn
    access-key-secret: C71rBAnW42cKGcHKbKIhTjvZNnr4rR
    bucket-name: wyz669

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  wechat:
    appid: wx35084d75f37075aa
    secret: 3677de592ec0aa4cec4ab76258eb5e7b
